version: "3.4"

services:

  nginx:
    restart: always
    build: ./nginx
    volumes:
    - nginx-www:/usr/share/nginx:rw
    - certs:/etc/ssl/certs:rw
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - apiexplorer

  apiexplorer:
    restart: always
    build: ./gunicorn
    image: tidr/apiexplorer
    volumes:
      - type: volume
        source: db
        target: /opt/apiexplorerdb/db
        volume:
          nocopy: true
    command: python3.6 run.py -p

  watchtower:
    restart: always
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  db:
  certs:
  nginx-www:
